ImmutableArrayDictionary new constructor
vostok/commons.collections pull request #10
Opened 2022-01-07 21:50 UTC by deniaa

2022-01-08 12:10 UTC, KungA requested changes

2022-01-08 12:10 UTC, KungA commented on Vostok.Commons.Collections/ImmutableArrayDictionary.cs
> +                pairs[index++] = new Pair(key, value, this.keyComparer.GetHashCode(key));
а может вообще тут в конструкторе только капасити принимать, и сделать Set без локов и проверок делающий то же самое?

тогда енумерабл выкинется ещё

2022-01-09 17:25 UTC, deniaa commented on Vostok.Commons.Collections/ImmutableArrayDictionary.cs
> +                pairs[index++] = new Pair(key, value, this.keyComparer.GetHashCode(key));
Прямо отдельный UnsafeSet(pair)? Даже без проверки на уникальность? И забив на то, что потеряется идея Immutable'сти?

2022-01-09 17:36 UTC, KungA commented on Vostok.Commons.Collections/ImmutableArrayDictionary.cs
> +                pairs[index++] = new Pair(key, value, this.keyComparer.GetHashCode(key));
ага, ты же это и сделал вроде как

2022-01-09 18:19 UTC, KungA commented on Vostok.Commons.Collections/ImmutableArrayDictionary.cs
> +                pairs[index++] = new Pair(key, value, this.keyComparer.GetHashCode(key));
про проверку уникальности не знаю, есть ли места когда она нужна нам при инициализации такой

2022-01-10 05:59 UTC, deniaa commented on Vostok.Commons.Collections/ImmutableArrayDictionary.cs
> +                pairs[index++] = new Pair(key, value, this.keyComparer.GetHashCode(key));
В принципе да, можно такой метод сделать. Все log.XXX экстеншны (и некоторые другие места) заполняют ImmutableArrayDictionary с нуля, которые не имеют шанса быть использованными многопоточно. Можно действительно завести SetUnsafe, который не будет пересоздавать ImmutableArrayDictionary и брать локи.

Сделаю.

2022-01-10 13:13 UTC, deniaa commented on Vostok.Commons.Collections/ImmutableArrayDictionary.cs
> +                pairs[index++] = new Pair(key, value, this.keyComparer.GetHashCode(key));
done

2022-01-10 14:00 UTC, KungA approved these changes

2022-01-10 14:06 UTC, KungA commented on Vostok.Commons.Collections/ImmutableArrayDictionary.cs
> +                    if (!overwrite || Equals(value, oldValue))
условие с Equals вроде лишнее

2022-01-11 09:30 UTC, merged